// Periodic table elements data
const ELEMENTS = [
  { number: 1, symbol: 'H', name: 'Hydrogen', family: 'Nonmetal' },
  { number: 2, symbol: 'He', name: 'Helium', family: 'Noble Gas' },
  { number: 3, symbol: 'Li', name: 'Lithium', family: 'Alkali Metal' },
  { number: 4, symbol: 'Be', name: 'Beryllium', family: 'Alkaline Earth' },
  { number: 5, symbol: 'B', name: 'Boron', family: 'Metalloid' },
  { number: 6, symbol: 'C', name: 'Carbon', family: 'Nonmetal' },
  { number: 7, symbol: 'N', name: 'Nitrogen', family: 'Nonmetal' },
  { number: 8, symbol: 'O', name: 'Oxygen', family: 'Nonmetal' },
  { number: 9, symbol: 'F', name: 'Fluorine', family: 'Halogen' },
  { number: 10, symbol: 'Ne', name: 'Neon', family: 'Noble Gas' },
  { number: 11, symbol: 'Na', name: 'Sodium', family: 'Alkali Metal' },
  { number: 12, symbol: 'Mg', name: 'Magnesium', family: 'Alkaline Earth' },
  { number: 13, symbol: 'Al', name: 'Aluminum', family: 'Metal' },
  { number: 14, symbol: 'Si', name: 'Silicon', family: 'Metalloid' },
  { number: 15, symbol: 'P', name: 'Phosphorus', family: 'Nonmetal' },
  { number: 16, symbol: 'S', name: 'Sulfur', family: 'Nonmetal' },
  { number: 17, symbol: 'Cl', name: 'Chlorine', family: 'Halogen' },
  { number: 18, symbol: 'Ar', name: 'Argon', family: 'Noble Gas' },
  { number: 19, symbol: 'K', name: 'Potassium', family: 'Alkali Metal' },
  { number: 20, symbol: 'Ca', name: 'Calcium', family: 'Alkaline Earth' },
  { number: 21, symbol: 'Sc', name: 'Scandium', family: 'Transition Metal' },
  { number: 22, symbol: 'Ti', name: 'Titanium', family: 'Transition Metal' },
  { number: 23, symbol: 'V', name: 'Vanadium', family: 'Transition Metal' },
  { number: 24, symbol: 'Cr', name: 'Chromium', family: 'Transition Metal' },
  { number: 25, symbol: 'Mn', name: 'Manganese', family: 'Transition Metal' },
  { number: 26, symbol: 'Fe', name: 'Iron', family: 'Transition Metal' },
  { number: 27, symbol: 'Co', name: 'Cobalt', family: 'Transition Metal' },
  { number: 28, symbol: 'Ni', name: 'Nickel', family: 'Transition Metal' },
  { number: 29, symbol: 'Cu', name: 'Copper', family: 'Transition Metal' },
  { number: 30, symbol: 'Zn', name: 'Zinc', family: 'Transition Metal' },
  { number: 31, symbol: 'Ga', name: 'Gallium', family: 'Metal' },
  { number: 32, symbol: 'Ge', name: 'Germanium', family: 'Metalloid' },
  { number: 33, symbol: 'As', name: 'Arsenic', family: 'Metalloid' },
  { number: 34, symbol: 'Se', name: 'Selenium', family: 'Nonmetal' },
  { number: 35, symbol: 'Br', name: 'Bromine', family: 'Halogen' },
  { number: 36, symbol: 'Kr', name: 'Krypton', family: 'Noble Gas' },
  { number: 37, symbol: 'Rb', name: 'Rubidium', family: 'Alkali Metal' },
  { number: 38, symbol: 'Sr', name: 'Strontium', family: 'Alkaline Earth' },
  { number: 39, symbol: 'Y', name: 'Yttrium', family: 'Transition Metal' },
  { number: 40, symbol: 'Zr', name: 'Zirconium', family: 'Transition Metal' },
  { number: 41, symbol: 'Nb', name: 'Niobium', family: 'Transition Metal' },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', family: 'Transition Metal' },
  { number: 43, symbol: 'Tc', name: 'Technetium', family: 'Transition Metal' },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', family: 'Transition Metal' },
  { number: 45, symbol: 'Rh', name: 'Rhodium', family: 'Transition Metal' },
  { number: 46, symbol: 'Pd', name: 'Palladium', family: 'Transition Metal' },
  { number: 47, symbol: 'Ag', name: 'Silver', family: 'Transition Metal' },
  { number: 48, symbol: 'Cd', name: 'Cadmium', family: 'Transition Metal' },
  { number: 49, symbol: 'In', name: 'Indium', family: 'Metal' },
  { number: 50, symbol: 'Sn', name: 'Tin', family: 'Metal' },
  { number: 51, symbol: 'Sb', name: 'Antimony', family: 'Metalloid' },
  { number: 52, symbol: 'Te', name: 'Tellurium', family: 'Metalloid' },
  { number: 53, symbol: 'I', name: 'Iodine', family: 'Halogen' },
  { number: 54, symbol: 'Xe', name: 'Xenon', family: 'Noble Gas' },
  { number: 55, symbol: 'Cs', name: 'Cesium', family: 'Alkali Metal' },
  { number: 56, symbol: 'Ba', name: 'Barium', family: 'Alkaline Earth' },
  { number: 57, symbol: 'La', name: 'Lanthanum', family: 'Lanthanide' },
  { number: 58, symbol: 'Ce', name: 'Cerium', family: 'Lanthanide' },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', family: 'Lanthanide' },
  { number: 60, symbol: 'Nd', name: 'Neodymium', family: 'Lanthanide' },
  { number: 61, symbol: 'Pm', name: 'Promethium', family: 'Lanthanide' },
  { number: 62, symbol: 'Sm', name: 'Samarium', family: 'Lanthanide' },
  { number: 63, symbol: 'Eu', name: 'Europium', family: 'Lanthanide' },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', family: 'Lanthanide' },
  { number: 65, symbol: 'Tb', name: 'Terbium', family: 'Lanthanide' },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', family: 'Lanthanide' },
  { number: 67, symbol: 'Ho', name: 'Holmium', family: 'Lanthanide' },
  { number: 68, symbol: 'Er', name: 'Erbium', family: 'Lanthanide' },
  { number: 69, symbol: 'Tm', name: 'Thulium', family: 'Lanthanide' },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', family: 'Lanthanide' },
  { number: 71, symbol: 'Lu', name: 'Lutetium', family: 'Lanthanide' },
  { number: 72, symbol: 'Hf', name: 'Hafnium', family: 'Transition Metal' },
  { number: 73, symbol: 'Ta', name: 'Tantalum', family: 'Transition Metal' },
  { number: 74, symbol: 'W', name: 'Tungsten', family: 'Transition Metal' },
  { number: 75, symbol: 'Re', name: 'Rhenium', family: 'Transition Metal' },
  { number: 76, symbol: 'Os', name: 'Osmium', family: 'Transition Metal' },
  { number: 77, symbol: 'Ir', name: 'Iridium', family: 'Transition Metal' },
  { number: 78, symbol: 'Pt', name: 'Platinum', family: 'Transition Metal' },
  { number: 79, symbol: 'Au', name: 'Gold', family: 'Transition Metal' },
  { number: 80, symbol: 'Hg', name: 'Mercury', family: 'Transition Metal' },
  { number: 81, symbol: 'Tl', name: 'Thallium', family: 'Metal' },
  { number: 82, symbol: 'Pb', name: 'Lead', family: 'Metal' },
  { number: 83, symbol: 'Bi', name: 'Bismuth', family: 'Metal' },
  { number: 84, symbol: 'Po', name: 'Polonium', family: 'Metalloid' },
  { number: 85, symbol: 'At', name: 'Astatine', family: 'Halogen' },
  { number: 86, symbol: 'Rn', name: 'Radon', family: 'Noble Gas' },
  { number: 87, symbol: 'Fr', name: 'Francium', family: 'Alkali Metal' },
  { number: 88, symbol: 'Ra', name: 'Radium', family: 'Alkaline Earth' },
  { number: 89, symbol: 'Ac', name: 'Actinium', family: 'Actinide' },
  { number: 90, symbol: 'Th', name: 'Thorium', family: 'Actinide' },
  { number: 91, symbol: 'Pa', name: 'Protactinium', family: 'Actinide' },
  { number: 92, symbol: 'U', name: 'Uranium', family: 'Actinide' },
  { number: 93, symbol: 'Np', name: 'Neptunium', family: 'Actinide' },
  { number: 94, symbol: 'Pu', name: 'Plutonium', family: 'Actinide' },
  { number: 95, symbol: 'Am', name: 'Americium', family: 'Actinide' },
  { number: 96, symbol: 'Cm', name: 'Curium', family: 'Actinide' },
  { number: 97, symbol: 'Bk', name: 'Berkelium', family: 'Actinide' },
  { number: 98, symbol: 'Cf', name: 'Californium', family: 'Actinide' },
  { number: 99, symbol: 'Es', name: 'Einsteinium', family: 'Actinide' },
  { number: 100, symbol: 'Fm', name: 'Fermium', family: 'Actinide' },
  { number: 101, symbol: 'Md', name: 'Mendelevium', family: 'Actinide' },
  { number: 102, symbol: 'No', name: 'Nobelium', family: 'Actinide' },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', family: 'Actinide' },
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', family: 'Transition Metal' },
  { number: 105, symbol: 'Db', name: 'Dubnium', family: 'Transition Metal' },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', family: 'Transition Metal' },
  { number: 107, symbol: 'Bh', name: 'Bohrium', family: 'Transition Metal' },
  { number: 108, symbol: 'Hs', name: 'Hassium', family: 'Transition Metal' },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', family: 'Transition Metal' },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', family: 'Transition Metal' },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', family: 'Transition Metal' },
  { number: 112, symbol: 'Cn', name: 'Copernicium', family: 'Transition Metal' },
  { number: 113, symbol: 'Nh', name: 'Nihonium', family: 'Metal' },
  { number: 114, symbol: 'Fl', name: 'Flerovium', family: 'Metal' },
  { number: 115, symbol: 'Mc', name: 'Moscovium', family: 'Metal' },
  { number: 116, symbol: 'Lv', name: 'Livermorium', family: 'Metal' },
  { number: 117, symbol: 'Ts', name: 'Tennessine', family: 'Halogen' },
  { number: 118, symbol: 'Og', name: 'Oganesson', family: 'Noble Gas' }
];

// Get element by name (case-insensitive)
function getElementByName(name) {
  return ELEMENTS.find(el => el.name.toLowerCase() === name.toLowerCase());
}

// Get element by symbol
function getElementBySymbol(symbol) {
  return ELEMENTS.find(el => el.symbol.toLowerCase() === symbol.toLowerCase());
}

// Get element by number
function getElementByNumber(number) {
  return ELEMENTS.find(el => el.number === number);
}

// Get all element names for autocomplete
function getAllElementNames() {
  return ELEMENTS.map(el => el.name);
}
